### ISSUE TITLE
Modifier et finaliser la facture

### ISSUE THREAD

**Issue by danielrubango** [ledya-group/test_pyramide_hotel#5]

**Comment by pangakevin** [comment]
c'est fait

**Comment by danielrubango** [comment]
La facture n'est pas complete.
Je n'y vois pas de logo. Il faut l'ameliorer.

**Comment by pangakevin** [comment]
c'est fait ; y'avait un probleme avec le push qui est deja resolu

**Comment by pangakevin** [comment]
le denier commit sur front-end a la solution sur cela

**Comment by danielrubango** [comment]
Attend que je check

**Comment by danielrubango** [comment]
La facture n'est toujours pas présentable.
Le favicon doit être en *.ico, et pas *.gif.
D'ailleurs, rien n'apparaît chez moi. C'est toi, si ?

**Comment by danielrubango** [comment]
L'image apprait maintenant. Mais, s'il te plait, améliore la facture, si possible, essaie de refaire cela a partir de zero.

**Comment by pangakevin** [comment]
ok

**Comment by pangakevin** [comment]
comme je fini avec le stage  ce samedi alors des lundi je vais m'occuper de cela

**Comment by pangakevin** [comment]
c'est fait avec la facturation ainsi que l'extension de l'icon

**Comment by pangakevin** [comment]
apres leur remarque je vais modifier cela avec un autre design que je vais déjà mettre en place de que bon
