### ISSUE TITLE
bug : Dans le footer

### ISSUE THREAD

**Issue by pangakevin** [ledya-group/test_pyramide_hotel#6]
A partir de la branche Master : Dans le footer il faudra enlever la ligne row hors du footer sinon sa génère des bugs dans le site deja lance

**Comment by danielrubango** [comment]
Tu as une capture d'écran du mauvais affichage ? Je n'ai vois  absolument rien.

**Comment by pangakevin** [comment]
dans mon téléphone sa ne montre que le carrousel et le footer a moitié sans des écrit

**Comment by danielrubango** [comment]
Hum, veille donc corriger le problème, je pense que tu es le
front-designer... Bonne chance.

2017-09-26 22:07 GMT+01:00 panga kevin <notifications@github.com>:
