### ISSUE TITLE
Reservation en ligne et admin 

### ISSUE THREAD

**Issue by pangakevin** [ledya-group/test_pyramide_hotel#9]
la réservation en ligne et en mode admin ne répondent pas , en ajoutant un occupant sa donne une page d'erreur ainsi que lorsqu'on réserve en mode client

**Comment by danielrubango** [comment]
Ok... Des fois, fais des captures d'écran des erreurs que tu rencontres.
Je pense avoir corrigé l'erreur plus tôt.

**Comment by pangakevin** [comment]
c'est la même,  celle qui renvoie dans un message de woops......
